### ISSUE TITLE
Installing on portable vapoursynth?

### ISSUE THREAD

**Issue by manus693** [HolyWu/vs-realesrgan#14]
I'm getting this error:

`
python -m pip install --upgrade vsrealesrgan
Collecting vsrealesrgan
  Using cached vsrealesrgan-3.1.0-py3-none-any.whl (7.4 kB)
Collecting tqdm
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: numpy in d:\vapoursynth\lib\site-packages (from vsrealesrgan) (1.22.3)
Collecting VapourSynth>=55
  Using cached VapourSynth-58.zip (558 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\**\AppData\Local\Temp\pip-install-2415kpn4\vapoursynth_712c69d39f4a4718a3f6b523a85b39eb\setup.py", line 64, in <module>
          dll_path = query(winreg.HKEY_LOCAL_MACHINE, REGISTRY_PATH, REGISTRY_KEY)
        File "C:\Users\**\AppData\Local\Temp\pip-install-2415kpn4\vapoursynth_712c69d39f4a4718a3f6b523a85b39eb\setup.py", line 38, in query
          reg_key = winreg.OpenKey(hkey, path, 0, winreg.KEY_READ)
      FileNotFoundError: [WinError 2] The system cannot find the file specified

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\**\AppData\Local\Temp\pip-install-2415kpn4\vapoursynth_712c69d39f4a4718a3f6b523a85b39eb\setup.py", line 67, in <module>
          raise OSError("Couldn't detect vapoursynth installation path")
      OSError: Couldn't detect vapoursynth installation path
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by HolyWu** [comment]
Try https://pypi.org/project/VapourSynth/#files or https://pypi.org/project/VapourSynth-portable/#files. I don't use portable version so I'm not sure which one works.

**Comment by manus693** [comment]
It works then with 58, but now i cant install 
python -m pip install onnxruntime-gpu
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu

**Comment by HolyWu** [comment]
Currently you have to install nightly builds from https://test.pypi.org/project/ort-nightly-gpu/ before ONNX Runtime 1.12 is released for Python 3.10 support.

**Comment by manus693** [comment]
Ok, trying with python 3.8 then as 3.9 isnt supported anymore with VS R58

**Comment by manus693** [comment]
not working whatever I do. ERROR: Could not find a version that satisfies the requirement flatbuffers (from ort-nightly-gpu) (from versions: none)
ERROR: No matching distribution found for flatbuffers
Getting this error with 3.10 and the nightly edition. with 3.8 filters arent working, with 3.9 only VS R57 is working, and there i get that error from first post.

**Comment by manus693** [comment]
Finally got it working with python 3.8 and VS R58, a lot of library errors with onnx, had to add to windows environment libraries, and use scpripts and plugins from old Vapoursynth installs. Now I get the same fps with onnx as before, but gpu load is at 90-100%, before it was 10%. Don't understand this. So confusing, why is this so slow.
Using topaz I get 10xtimes the speed as this or with VSGAN.

**Comment by manus693** [comment]
I'm running on 1060 6GB, does this mean that with this update I can get a good speed increase (as GPU % has increased, and might seem like CPU has decreased) if I get RTX 2060 or 3060? I'm considering 3080ti, but very expensive.
Anyone have a speed comparisson between the different GPUs? 3060 to 3080ti is over the double in price here.
