### ISSUE TITLE
A way to use our own models?

### ISSUE THREAD

**Issue by lastrosade** [HolyWu/vs-realesrgan#16]
It would be sweet to be able to select our own models.

Maybe also support for pth format models?

Thanks.

**Comment by HolyWu** [comment]
It uses ONNX Runtime for inference and hence can only load onnx format models, not pth format (PyTorch) models. Did you want to load models trained by yourself?

**Comment by lastrosade** [comment]
Sorry, yes and no, I have one model that I trained myself and two that I have not.
I wish to be able to use them through Vapoursynth and thought that maybe this project could help me with that.

I have successfully converted my model to ONNX. However, I lack some of the data necessary to convert the third party models to ONNX.

**Comment by HolyWu** [comment]
I switched back to PyTorch again for inference and added a `model_path` parameter. The realesr-general-x4v3 model is also included.
