### ISSUE TITLE
[Feature Request] ncnn version

### ISSUE THREAD

**Issue by eapiova** [HolyWu/vs-realesrgan#19]
As https://github.com/xinntao/Real-ESRGAN provides a ncnn version, is it possible to implement it as a Vapoursynth filter?

**Comment by HolyWu** [comment]
It's redundant to implement an individual ncnn version. https://github.com/AmusementClub/vs-mlrt has added ncnn backend so you can perform inference on any model you like, as long as the model can be converted to onnx format first and ncnn has support for the OPs used inside the model.

**Comment by eapiova** [comment]
Thank you  very much for the explanation
