### ISSUE TITLE
[Feature Request] Face Enhance feature support

### ISSUE THREAD

**Issue by shr-go** [HolyWu/vs-realesrgan#22]
There is a feature in the official implementation of Real-ESRGAN that utilizes GFPGAN for face enhancement. 
Could you please add this feature to the implementation of vs-realesrgan? It would be very helpful for processing some videos.
Thank you very much!

**Comment by HolyWu** [comment]
I ported CodeFormer in https://github.com/HolyWu/vs-codeformer and it allows you to specify a background clip which has been upsampled (not restricted to Real-ESRGAN like in the official implementation).
