### ISSUE TITLE
Full Example Script

### ISSUE THREAD

**Issue by AIManifest** [HolyWu/vs-realesrgan#27]
Hi all,

Kindly requesting if anyone has a full example inference script for vs-realesrgan? No clue how to use vapoursynth, and so many errors. Also, the example usage on Readme is minimal, so not even sure how to initiate the clip. 

Thank you in advance for your time.

**Comment by HolyWu** [comment]
You need to at least have basic knowledge about VapourSynth (and of course Python language). Maybe start by reading http://www.vapoursynth.com/doc/index.html and https://jaded-encoding-thaumaturgy.github.io/JET-guide/ first.

**Comment by AIManifest** [comment]
I understand that my friend, I am have more than proficient knowledge with Python and have read the Vapoursynth docs, but to install it on Linux in Jupyter lab cost me literally 3 hours (my fault of course for being stubborn). That’s why I’m asking for a simple inference script and a reliable installation guide as the information on this repo and on Vapoursynth is not exactly working out of the box. All I’m asking for is a little assistance. Thank you for your time.
