### ISSUE TITLE
 Is this speed normal?

### ISSUE THREAD

**Issue by KiritoGuugk** [HolyWu/vs-realesrgan#29]
On my RTX 4060 8GB, the processing speed of model 1(RealESRGAN_x2plus) for 720p video is only 1.5fps. Is this speed normal? My configuration is as follows, and it was based on the vs script I found online. Is this configuration correct?

```
import vapoursynth as vs
from vsrealesrgan import realesrgan

core = vs.core
clip = core.ffms2.Source(source=in_filename)

clip = core.resize.Bilinear(clip=clip, format=vs.RGBH, matrix_in_s="709")

clip = realesrgan(
    clip=clip,
    model=1,
    trt=True,
    trt_optimization_level=0,
)

clip = core.resize.Bilinear(
    clip=clip,
    format=vs.YUV420P8,
    matrix_s="2020ncl"
)

clip.set_output()
```

**Comment by HolyWu** [comment]
Why are you using `trt_optimization_level=0`? Also try `num_streams=2` and/or `num_batches=2`.

**Comment by KiritoGuugk** [comment]
OK, as I said, I’m just looking for scripts online and modifying them. I don’t fully understand their meaning. After your reminder, I checked the `__init__.py` file. So, should I set the `trt_optimization_level` to 5?

**Comment by KiritoGuugk** [comment]
Now I get 2.8 fps after set `trt_optimization_level=3` `num_streams=2` `num_batches=2`. Is this speed typical？

**Comment by HolyWu** [comment]
Seems reasonable to me. I got 3.35 fps on my 4060 Ti 16GB.

**Comment by KiritoGuugk** [comment]
Thank you very much for your assistance !
