### ISSUE TITLE
How can I make it in realtime in mpv?

### ISSUE THREAD

**Issue by KiritoGuugk** [HolyWu/vs-realesrgan#30]
I add `ctrl+alt+= apply-profile "realesrgan"` in `input.conf`  and add this in `mpv.conf`:
```
[realesrgan]
vf=vapoursynth="/home/xxx/.config/mpv/realesrgan.vpy":buffered-frames=4:concurrent-frames=32
hr-seek-framedrop=no
video-sync=audio
```

I modified my vs script as :
```
import vapoursynth as vs
from vsrealesrgan import realesrgan

core = vs.core
clip = video_in

clip = core.resize.Bilinear(clip=clip, format=vs.RGBH, matrix_in_s="709")

clip = realesrgan(
    clip=clip,
    model=102,
    device_index=0,
    num_streams=2,
    num_batches=2,
    trt=True,
    trt_optimization_level=3,
)

clip = core.resize.Bilinear(
    clip=clip,
    format=vs.YUV420P8,
    matrix_s="2020ncl"
)

clip.set_output()
```
but I just got mpv crash with:
```
Property read unsuccessful due to missing key but no error output: _MP_IMAGE
terminate called without an active exception
[1]    66435 IOT instruction (core dumped)  mpv --player-operation-mode=pseudo-gui --msg-level=all=debug
```

If I change  `clip = video_in` to `clip = core.ffms2.Source(source=in_filename)` , I can use ffplay via `vspipe -c y4m --arg in_filename='xxx.mp4'  /home/xxx/.config/mpv/realesrgan.vpy  - | ffplay -f yuv4mpegpipe -i pipe:` to play it correctly.

I know this may not be an issue with vs-realesrgan, but I have no other choice, as I couldn’t find any solution online. Therefore, I am trying to open this issue.

**Comment by KiritoGuugk** [comment]
> have you tried with num_streams=**1** instead of **2** ? (depending on you gpu that might be faster)

Actually, I don't even know where it will take effect. I set 2 because the author suggests me to try this parameter. 😂
https://github.com/HolyWu/vs-realesrgan/issues/29#issuecomment-2462340930

**Comment by Selur** [comment]
He suggested _and/or_ , for me using num_streams=1 was sometimes faster with batch > 1

**Comment by KiritoGuugk** [comment]
> He suggested _and/or_ , for me using num_streams=1 was sometimes faster with batch > 1

Thank you for your suggestion.☺️
