### ISSUE TITLE
In v5.1.0 modelopt library is missing

### ISSUE THREAD

**Issue by dan64** [HolyWu/vs-realesrgan#31]
Hello HolyWu,

   first of all i wanted to thank you for the fantastic work you did on vs-realesrgan v5.1.0. 
   On my windows system the resizing speed  increase of about 2.6x.

   When I use your package is displayed the following message:

   _Unable to import quantization op. Please install modelopt library ([https://github.com/NVIDIA/TensorRT-Model...stallation](https://github.com/NVIDIA/TensorRT-Model-Optimizer?tab=readme-ov-file#installation)) to add support for compiling quantized models_

   Since the installation steps described in https://nvidia.github.io/TensorRT-Model-Optimizer/getting_started/windows/_installation_standalone.html are quite complex, I'd like to know if the installation of this library is necessary and if there are further improvements in the resizing speed using it.

Thank you,
Dan

**Comment by HolyWu** [comment]
None of ModelOpt's functionality is used so you can safely ignore that message.
