### ISSUE TITLE
How about images

### ISSUE THREAD

**Issue by alexandar-m** [HolyWu/vs-realesrgan#5]
Can you rework it so it can do one image also?
Thanks

from vsrealesrgan import RealESRGAN
ret = RealESRGAN(clip)

**Comment by HolyWu** [comment]
You have to use a filter like https://github.com/vapoursynth/vs-imwri which returns a VideoNode.
Then converts the img to floating-point 32-bit by something like `img = img.resize.Bicubic(format=vs.RGBS)`.
