### ISSUE TITLE
[REQ] SwinIR port

### ISSUE THREAD

**Issue by forart** [HolyWu/vs-realesrgan#6]
Hi there, 1st of all thanks for your great work in porting all those goods to VapourSynth !

Dunno if it's the right place to ask, but it would be great to have [SwinIR](https://github.com/JingyunLiang/SwinIR) by @JingyunLiang in VS too:
![arXiv](https://raw.githubusercontent.com/JingyunLiang/SwinIR/main/figs/real_world_image_sr.png)

[SwinIR: Image Restoration Using Swin Transformer](https://github.com/JingyunLiang/SwinIR#swinir-image-restoration-using-swin-transformer)

Hope that inspires !

**Comment by HolyWu** [comment]
Done.
