### ISSUE TITLE
'vapoursynth.VideoFrame' object is not subscriptable

### ISSUE THREAD

**Issue by splinter21** [HolyWu/vs-realesrgan#9]
Error on frame 15 request:
'vapoursynth.VideoFrame' object is not subscriptable

py3.6.4
vs.core.version:
VapourSynth Video Processing Library\nCopyright (c) 2012-2018 Fredrik Mellbin\nCore R44\nAPI R3.5\nOptions: -\n
torch.__version__:
1.10.0+cu111

vpy:
import vapoursynth as vs
import sys
sys.path.append("C:\C\Transcoding\VapourSynth\core64\plugins\Scripts")
import mvsfunc as mvf
sys.path.append(r"C:\Users\liujing\AppData\Local\Programs\Python\Python36\Lib\site-packages\vsrealesrgan")
from vsrealesrgan import RealESRGAN

core = vs.get_core(accept_lowercase=True)
source = core.ffms2.Source(sourcename)
source = mvf.ToRGB(source,depth=32)
source = RealESRGAN(source)
source= mvf.ToYUV(source,depth=16)
source.set_output()

**Comment by HolyWu** [comment]
Your VapourSynth version is too outdated. Try updating first.

**Comment by splinter21** [comment]
> Your VapourSynth version is too outdated. Try updating first.

I update py version to py3.9.5 now.
@HolyWu When I update the version of vs to R54, I meet the same question when processing "source = RealESRGAN(source)"

------------------------------------

When I update it to >=R54-test2-API4 (R54-test2-API4,R55,R56,R57), error happen when processing "source = mvf.ToRGB(source,depth=32)":
File "C:\Program Files\Python39\lib\site-packages\mvsfunc.py", line 446, in ToRGB
clip = core.fmtc.matrix(clip, mat=matrix, fulls=fulls, fulld=fulld, col_fam=vs.RGB)
File "src\cython\vapoursynth.pyx", line 2531, in vapoursynth.Function.__call__
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte

(But "source = RealESRGAN(source)" can be processed.)
mvsfunc.py is from https://github.com/HomeOfVapourSynthEvolution/mvsfunc/blob/master/mvsfunc.py, the latest version.

What can I do to process the whole pipeline?

**Comment by splinter21** [comment]
I update the version of fmtconv.dll and fix the problem QAQ.
So these pytorch scripts for vs only supports version > R54, am I right?

**Comment by HolyWu** [comment]
Yes, the version requirement is specified [here](https://github.com/HolyWu/vs-realesrgan/blob/b66f5b149b5286b6cbf7ac4f80e00b8f8bd6d7de/setup.cfg#L25).
